# Generated by Django 3.2.3 on 2021-05-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=50)),
                ('positions', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('requirements', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=5, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(1, 'Quan Ly'), (2, 'Nhan Vien')], default=2)),
                ('phone', models.CharField(max_length=20)),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('N', 'Nhan Su'), ('H', 'Hanh Chinh'), ('D', 'Dao Tao')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('card_id', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.recruitment')),
            ],
        ),
    ]
